### ISSUE TITLE
state_map Issue

### ISSUE THREAD

**Issue by jer78** [postlund/home-card#16]
I use a binary_sensor.people_home which tracks both my wife and my device_trackers and gives a boolean "On" or "Off".

However on two different iOS devices the UI reacts differently when the binary_sensor is "On"

1. If I use this...my iPhone and Safari web browser do not display the car but the iPad does

```
                - type: car
                  entity: binary_sensor.people_home
                  state_map:
                    On: 'home'
                    'off': 'not_home'
```

2. This displays correctly iPhone and Safari but not iPad iOS app.

```
                - type: car
                  entity: binary_sensor.people_home
                  state_map:
                    'on': 'home'
                    'off': 'not_home'
```

3. Note on all devices, unless I use quotes for the 'home' and 'not_home', no car displays so I'm guessing the code is specifically looking for an exact match rather than looking for variations of "on", "On", "true", "True" etc. 

Full config below for reference

```
  name: My Home
  views:
    - icon: mdi:home-assistant
      path: home
      title: Home
      background: paper-card
      cards:
        - type: vertical-stack
          cards: 
            - type: custom:search-card
              max_results: 5
            - type: 'custom:home-card'
              theme: two_story_with_garage
              weather: weather.dark_sky
              entities:
                - type: door
                  entity: lock.front_door
                  state_map:
                    'locked': 'on' 
                    'unlocked': 'off'
                - type: garage
                  entity: cover.my_garage_door
                - type: upstairs_light
                  entity: group.second_floor_lights
                - type: downstairs_light
                  entity: group.main_floor_lights
                - type: car
                  entity: binary_sensor.people_home
                  state_map:
                    On: 'home'
                    'off': 'not_home'
```
