### ISSUE TITLE
Resources actions do not work

### ISSUE THREAD

**Issue by jer78** [postlund/home-card#17]
Both the tap_action and hold_action do not work as intended but the more-info always displays.

```
              resources:
                - entity: input_boolean.home_scene
                  icon: mdi:home
                  tap_action: 
                    action: toggle
                  hold_action:
                    action: none
                - entity: input_boolean.guest_mode_bedroom
                  icon: mdi:account-multiple
                  tap_action: 
                    action: toggle
                  hold_action:
                    action: none
```
