### ISSUE TITLE
custom_themes not work

### ISSUE THREAD

**Issue by pex81** [postlund/home-card#27]
i'm trying the custom_themes but the style doesn't seem to work correctly.

```
          - type: custom:home-card
            weather: weather.dark_sky
            theme: my_home
            background: transparent
            entities:
              - type: car
                entity: person.giuseppe
                state_map:
                  off: not_home
                  on: home
              - type: sprinkler
                entity: input_boolean.prova                      
            custom_themes:
              my_home:
                house: house.png
                overlay_actions:
                  '*':
                    tap_action:
                      action: toggle
                  car:
                    tap_action:
                      action: more-info
                overlays:
                  car:
                    home:
                      - image: car.png
                        style:
                          width: 8%
                          left: 60%
                          top: 50%
                    not_home:
                      - image: car.png
                        style:
                          left: 40%
                          top: 40%                
                  sprinkler:
                    on:
                      - image: sprinkler-on.png
                        style:
                          left: 10%
                          top: 10%
                    off:
                      - image: sprinkler-off.png
                        style:
                          left: 40%
                          top: 40%
```
if I remove the "," the style work.
<img width="1310" alt="Schermata 2021-06-30 alle 18 02 32" src="https://user-images.githubusercontent.com/58252398/123994509-ba2d8300-d9cd-11eb-8235-cda271bdff5d.png">
