### ISSUE TITLE
Door status inverted

### ISSUE THREAD

**Issue by Hertizch** [postlund/home-card#5]
My door sensor shows 'off' when closed and 'on' when open. I've tried to use 'state_map' to invert the states but the door is always shown the door-open.png image.

```yaml
- type: door
  entity: binary_sensor.front_door_contact
  state_map:
    on: "off"
    off: "on"
```

**Comment by postlund** [comment]
Hmm, strange. Using `state_map` seems to work just fine for me in my example (using an `input_boolean` to simulate the door). Also using one of the demo binary sensors seems to work in the same way as well. The code generated by the lovelace editor looks like this:

```yaml
entities:
  - entity: input_boolean.demo_door
    type: door
    state_map:
      'on': 'off'
      'off': 'on'
```

But the quoting shouldn't be a problem. Can you double check the sensor state and refresh the UI after transition? Shouldn't be problem, but I don't really understand what is wrong here.
